feedjira/feedjira

.gitignore, .travis.yml, Gemfile, spec/feedjira/feed_spec.rb, spec/feedjira/parser/atom_feed_burner_entry_spec.rb, spec/feedjira/parser/atom_feed_burner_spec.rb, spec/feedjira/parser/rss_feed_burner_entry_spec.rb
Coming back to this project after quite a bit of time and found the project in a bad state.
My initial goal is to get Travis back to a green state and build up from there. To that end, I found and fixed some flickering tests, dropped really old Ruby versions and have allowed JRuby to fail.
You might notice that this PR drops support for Ruby 1.9.3 and 2.0.0, I feel like this is fair given the state of those rubies:
https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/
In fact, with Ruby 2.4 just around the corner, expect to see 2.1 dropped soon too:
https://www.ruby-lang.org/en/news/2016/09/08/ruby-2-4-0-preview2-released/
=> Properly add JRuby to travis

.rubocop.yml, .travis.yml
When I pulled in #317 I broke the broken JRuby build because I was using an older JRuby. This PR upgrades our JRuby to 9000. While I was at it, I also locked Rubocop to use Ruby 2.1. I upgraded my local clone to use 2.3 and it was making suggestions that would break on older versions.
=> Use JRuby 9000 on Travis

.travis.yml
Per this page:
https://docs.travis-ci.com/user/caching/#Bundler
Caching Bundler is not yet the default behavior.
=> Cache bundler to speed up builds

.travis.yml, lib/feedjira/parser/atom.rb, lib/feedjira/parser/google_docs_atom.rb, lib/feedjira/parser/itunes_rss.rb, spec/feedjira/feed_spec.rb, spec/feedjira/parser/itunes_rss_spec.rb, spec/sample_feeds.rb, spec/sample_feeds/ITunesWithSingleQuotedAttributes.xml
I came across an iTunes RSS feed that was perfectly valid but `Feedjira::Parser::ITunesRSS.able_to_parse?` was returning `false` because the feed used single-quotes instead of double-quotes around attributes. Specifically, around:
```xml
<rss version='2.0' xmlns:itunes='http://www.itunes.com/dtds/podcast-1.0.dtd'> 
```
This pull request updates the regular expression to allow either single or double quotes, as well as cleaning up a few other related issues.
=> Allow single quoted attributes in iTunes RSS feeds

.travis.yml
Disable danger until we figure out how to resolve builds that fail due to danger breaking.
Tracked in issue #330 merge before https://github.com/feedjira/feedjira/pull/277
@krasnoukhov look good?
I think we should leave the Dangerfile around while we see if we can get actionable messages out of danger.
=> disable danger

feedjira.gemspec, fixtures/vcr_cassettes/fetch_failure.yml, fixtures/vcr_cassettes/parse_error.yml, fixtures/vcr_cassettes/success.yml, spec/feedjira/feed_spec.rb, spec/spec_helper.rb
there are three tests in feed_spec that require network to pass.
PR #297 fixes the immediate issue by making the test general enough to
pass when the response from the server changes somewhat.
PR #300 fixes the network issue, but uses specific stubs. I would say
this method is no better or worse than this one, however it does require
knowing that you are stubbing the request and manually keeping responses
up to date.
This method acts the most like actually hitting the network and will
work on an airplane.
=> use vcr to stub network requests

lib/feedjira/parser/itunes_rss.rb, spec/feedjira/parser/itunes_rss_spec.rb, spec/sample_feeds/itunes.xml
It is documented here: https://help.apple.com/itc/podcasts_connect/#/itcb54353390
=> Add a missing podcast attribute `itunes_complete` to ITunesRSS

lib/feedjira.rb, lib/feedjira/feed.rb, lib/feedjira/parser/atom_youtube.rb, lib/feedjira/parser/atom_youtube_entry.rb, spec/feedjira/parser/atom_youtube_entry_spec.rb, spec/feedjira/parser/atom_youtube_spec.rb, spec/sample_feeds.rb, spec/sample_feeds/youtube_atom.xml
Original PR here: https://github.com/feedjira/feedjira/pull/280
YouTube just released an updated RSS feed format. New feeds look like this:
https://www.youtube.com/feeds/videos.xml?channel_id=UCK8sQmJBp8GCxrOtXWBpyEA
You can see that the feed no longer contains any standard Atom fields that give any information about the video other than the link or the title.
This PR makes the fields from some of the included Atom extensions that provide information about the video available via a custom parser.
=> Support for new YouTube Atom format

.travis.yml
=> Add Danger back to Travis

lib/feedjira.rb, lib/feedjira/date_time_utilities.rb, lib/feedjira/feed.rb, lib/feedjira/feed_entry_utilities.rb, lib/feedjira/version.rb, spec/feedjira/date_time_utilities_spec.rb, spec/feedjira/feed_entry_utilities_spec.rb
While parsing a lot of foreign feeds I've seen a lot of crazy DateTimes inside these feeds. Because feedjira expects a feed to use ISO 8601 DateTime Format, we would loos these feeds date information. 
In fact, using non ISO 8601 DateTime Format is - in most cases - a violation of the feeds doctype. But I think it is OK to handle these violations, because there are a lot of them.
I've startet with spanish and one japanese example. Maybe I will contribute more handlers in the future.
=> Enhanced DateTime Handling for supporting non ISO 8601 DateTime Strings

lib/feedjira/preprocessor.rb, spec/feedjira/preprocessor_spec.rb, spec/sample_feeds.rb, spec/sample_feeds/AtomEscapedHTMLInPreTag.xml
=> Don't unescape escaped HTML inside XHTML content node.

lib/feedjira/date_time_utilities.rb
The ruby Default Parser sometimes does strange things. For example it parses `水, 31 8 2016 07:37:00 PDT'` to `2016-12-31 14:37:00.000000000 +0000`
So it's necessary to first check for "special pattern" and then use the default parser.
=> Changed the direction of DateParsers

lib/feedjira/parser/itunes_rss.rb, lib/feedjira/parser/rss.rb, lib/feedjira/parser/rss_feed_burner.rb, spec/feedjira/parser/itunes_rss_spec.rb, spec/feedjira/parser/rss_feed_burner_spec.rb, spec/feedjira/parser/rss_spec.rb, spec/sample_feeds/TenderLovemaking.xml, spec/sample_feeds/itunes.xml
These elements are part of the [RSS 2.0 specification](http://cyber.harvard.edu/rss/rss.html).
According to the [RSS Advisory Board](http://www.rssboard.org/rss-profile#element-channel-ttl):
> Twenty-one percent of surveyed feeds included a `ttl` element.
That survey was taken in 2007. The practice of including a `ttl` element has even wider adoption today, especially among podcast feeds.
It is also mentioned on the original [`syndication-dev` mailing list](http://lists.apple.com/archives/syndication-dev/2005/Nov/msg00002.html) in 2005:
> The ttl tag stands for "time-to-live". It is an optional integer value that controls how many minutes iTunes will wait between checking for changes in a podcast. If no time-to-live is set on the podcast, the updater job assumes a time-to-live of 24 …
=> Add ttl and last_built elements to RSS and ITunesRSS parsers

CHANGELOG.md, lib/feedjira/version.rb
We have a healthy list of authors this release,
@jfiorato
@krasnoukhov
@PascalTurbo
@sferik
@knu
Thanks so much for your work improving Feedjira. Assuming the build comes back green I propose we call this 2.1.0 tomorrow. Any objections?
=> update changelog and bump version

.gitignore, .rubocop.yml, Rakefile, feedjira.gemspec, lib/feedjira/core_ext/string.rb, lib/feedjira/core_ext/time.rb, lib/feedjira/date_time_utilities.rb, lib/feedjira/date_time_utilities/date_time_language_parser.rb, lib/feedjira/date_time_utilities/date_time_pattern_parser.rb, lib/feedjira/feed.rb, lib/feedjira/feed_entry_utilities.rb, lib/feedjira/feed_utilities.rb, lib/feedjira/parser.rb, lib/feedjira/parser/atom_youtube_entry.rb, lib/feedjira/parser/google_docs_atom.rb, lib/feedjira/parser/google_docs_atom_entry.rb, lib/feedjira/parser/itunes_rss_owner.rb, lib/feedjira/parser/podlove_chapter.rb, lib/feedjira/preprocessor.rb
Initial fix for #345
I've reenabled rubocop for documentation (even if it lacks of checking the single methods) and suppress warnings for undocumented modules and classes.
@HParker Could you pleas review the changes if it fit's our needs
=> Added YARD for documentation

lib/feedjira/parser/atom_feed_burner.rb, spec/feedjira/parser/atom_feed_burner_spec.rb, spec/sample_feeds.rb, spec/sample_feeds/GiantRobotsSmashingIntoOtherGiantRobots.xml
Fixes #327 
Changed AtomFeedBurner parser so that it correctly parses feedburner atom feeds in the new style some feeds seem to be using. In this alternate style:
- the link to the feed webpage may be a plain ```<link>``` element without the type="text/html" attribute we usually expected
- the link to the feed itself may be a ```<atom10:link>``` element instead of the ```<link>``` element we usually expected (with type="application/atom+xml")
The way the change is implemented, old-style values will take precedence if present in the feed. Only if the new style is used will the parser use the new locations for the url and feed_url values.
=> Fix feedburner url

lib/feedjira/configuration.rb, lib/feedjira/feed.rb, spec/feedjira/feed_spec.rb
This allows users to explicitly set the list of parsers that will be
used for parsing feeds.
This is a step towards #370
=> Support configuration for parsers

lib/feedjira/feed.rb
if i understand correctly, the whole idea of faraday is to provide a common api over multiple http clients. 
so say, i'm using httpclient in my project, i would want feedjira to use httpclient as well. 
what i would do is to set the default_adapter `Faraday.default_adapter = :httpclient`.
=> Use the default adapter configured

lib/feedjira/parser/atom_feed_burner.rb, spec/feedjira/parser/atom_feed_burner_spec.rb
Fixes https://github.com/feedjira/feedjira/issues/376
Adds back the ability to set values to "url" and "feed_url" attributes of AtomFeedBurner instances, that was removed in PR https://github.com/feedjira/feedjira/pull/366/files
=> Fixed setting values in 'url', 'feed_url' attributes in atom feeds

lib/feedjira/feed.rb
This fixes #374. `#default_adapter` might have arguments, which needs to be passed into `#adapter(key, *args)`, so we need to splat here.
=> Splat default_adapter

lib/feedjira/parser/itunes_rss.rb, lib/feedjira/parser/itunes_rss_item.rb, spec/feedjira/parser/itunes_rss_item_spec.rb, spec/feedjira/parser/itunes_rss_spec.rb, spec/sample_feeds/itunes.xml
iOS 11 will have support for new podcast tags. Let's parse 'em!
http://podcasts.apple.com/resources/spec/ApplePodcastsSpecUpdatesiOS11.pdf
=> Support for parsing new iTunes podcasting tags

lib/feedjira/parser/json_feed.rb, lib/feedjira/parser/json_feed_item.rb, spec/feedjira/parser/json_feed_item_spec.rb
The JSON Feed format defines many other attributes than are defined in the JSONFeed/JSONFeedItem classes, so it is desirable to give full access to those via the `json` accessor.
Also, the "tags" element defined in JSON Feed should correspond to the `categories` accessor that is common to other feed item classes.
=> Add attributes to JSON Feed classes

lib/feedjira/feed_entry_utilities.rb, spec/feedjira_spec.rb, spec/sample_feeds.rb, spec/sample_feeds/InvalidDateFormat.xml
This code was raising a NoMethodError when trying to compare a nil
unparseable date with a previous successfully parsed date.
=> Prevent errors when a feed has multiple dates and some are unparseable

lib/feedjira/parser/atom_youtube_entry.rb
Channel IDs can occur in entry elements received
through YouTube's PubSubHubbub push notifications.
https://developers.google.com/youtube/v3/guides/push_notifications
=> Add channel id element to AtomYoutubeEntry parser

.travis.yml
I added this a while back when I was active on Feedjira, but now that I've transitioned maintainership over to the very talented team we have now, this is stale.
=> Remove Stale Travis Webhook

lib/feedjira/parser/atom_feed_burner.rb
I came across [a site](https://2ality.com/) that Feedjira miss-identifies as being able to parse as a `Feedjira::Parser::AtomFeedBurner` feed.
The regex for `AtomFeedBurner` only check for the presence of the strings "Atom" and "feedburner" which might be too easy for a non-feed to satisfy. This adds the requirement of also needing a `<feed` tag.
=> Check for presence of <feed> tag on feedburner/atom feeds.

CHANGELOG.md, lib/feedjira/atom_entry_utilities.rb, spec/feedjira/parser/atom_entry_spec.rb, spec/feedjira/parser/atom_spec.rb
Some Atom feeds provide entry titles in a non-plain text format like HTML, but you normally wouldn't expect that and there is no way to tell if an entry title returned from a Feedjira entry object is actually in HTML.
This PR makes `title()` methods of Atom entry classes always return a plain text by stripping off markups when the title element has a type of (X)HTML/XML.  For accessing raw contents, the new
methods `title_type` and `raw_title` are added.
P.S. This PR is marked as WIP because the work is based on #422 which aims to avoid duplicating the same code to all Atom entry classes.
=> Make `#title` of Atom entry classes always return a plain text

lib/feedjira/parser/itunes_rss_category.rb
Capturing the given block using `Kernel#proc` is deprecated; use `&block` instead.
=> Fix warnings in Ruby 2.7

.travis.yml
We don't have an official "Supported versions" list, but I know that 2.2-2.4 is not correct anymore. I am guessing it is best to test the last 3 major versions for now. That should get us all ruby versions back to 2017, which seems appropriately cautious for now.
=> Test on last 3 major versions

lib/feedjira/parser/itunes_rss.rb
Adding alias will provide more rube style way off checking content of managingEditor
issue: #439
=> Add alias for managingEditor element

.github/workflow/ci.yml
Now Travis CI builds won't run as quickly as before and jobs tend to be stuck in the queue for hours.
I'm not sure how it's going to be after the migration from travis-ci.org to travis-ci.com, but I think it's time for us to take action and prepare for service degradation.
GitHub Actions offers 2,000 free build minutes per month for OSS projects, but since we have a 5x3 matrix our usage may exceed the limit, in which case we'll need to split the matrix and use both GitHub and Travis CI.
=> Run CI using GitHub Actions

.rubocop.yml, feedjira.gemspec
This makes the required Ruby version in the gemspec match the version configured for RuboCop, and the set of Rubies tested in CI.
Fixes #447.
=> Fix required ruby version

feedjira.gemspec, spec/spec_helper.rb
VCR is no longer actually used in the specs, since the feching portion of Feedjira has been removed.
=> Remove unused VCR dependency

lib/feedjira/parser/atom.rb, spec/feedjira/parser/atom_spec.rb, spec/sample_feeds.rb, spec/sample_feeds/atom_simple_single_entry.xml, spec/sample_feeds/atom_simple_single_entry_link_self.xml
Hello and thanks for building and maintaining feedjira!
I noticed that when an Atom feed only include one link, e.g. `<link href="http://example.org/"/>` in the top-level element, it will automatically be parsed as both `url` _and_ `feed_url`. This PR changes `feed_url` to only look for links with the `rel="self"`-attribute and removes the fallback for `url` to the last link in the document.
The current way to look for `feed_url` dates back to 2009 (https://github.com/feedjira/feedjira/commit/d0854f46469248aa2d6ef4d35bef4f8222278f77) and mentions that this will fix links that "don't confirm to the standard" (note that the way the parser looks for `feed_url` has changed since then (https://github.com/feedjira/feedjira/commit/4b4d803bfec9c2e7964d96f64d9c4f861614143c). I think falling back …
=> Atom url parsing

lib/feedjira/configuration.rb, spec/feedjira_spec.rb, spec/sample_feeds.rb, spec/sample_feeds/itunes_feedburner.xml
When an Itunes feed is published on Feedburner, it parses it as a
Feedburner feed, which doesn't capture the enclosure url for the podcast
download. This change moves Itunes feed parsing above Feedburner, so
that for these cases, the feed will instead be parsed as an Itunes feed
rather than a Feedburner feed. This will ensure that the enclosure url
will be available.
Fixes [https://github.com/feedjira/feedjira/issues/464][464] and probably fixes [https://github.com/feedjira/feedjira/issues/428][428].
[464]: https://github.com/feedjira/feedjira/issues/464
[428]: https://github.com/feedjira/feedjira/issues/428
=> Fix Feedburner Itunes feed parsing

lib/feedjira/core_ext/time.rb, spec/feedjira/core_ext/time_spec.rb, spec/support/coverage.rb
This adds missing test coverage for `core_ext/time`. This also surfaced
a code issue with the second condition. Ruby `DateTime` does not
implement the `#utc` method so calling `datetime.to_datetime.utc`
actually raises an error. I removed this in favor of calling `.to_time`
on anything that responds to it.
```irb
> Date.today.to_datetime.utc
(irb):6:in `<main>': undefined method `utc' for #<DateTime: 2023-10-22T00:00:00+00:00 ((2460240j,0s,0n),+0s,2299161j)> (NoMethodError)
```
=> Coverage: add tests for `core_ext/time`

spec/feedjira/feed_spec.rb
This adds missing test coverage for `Feed.add_common_feed_elements` and
`Feed.add_common_feed_entry_elements`. I don't love these because they
only test the highest level, and they have side effects on the other
classes that will persist throughout the tests. Without digging into
`SAXMachine` internals, though, there's not much to do.
=> Coverage: add tests for Feed methods

lib/feedjira/core_ext/date.rb
This removes the unused method `Date.feed_utils_to_local_time`.
=> remove unused `Date` core extension

lib/feedjira.rb
Hello!
I encountered a feed that had a very long base64 encoded string from https://www.rss.style at the beginning of its RSS XML file.
The previous limit of 2000 characters was insufficient and in turn `able_to_parse?` always returned `false`.
This commit doubles that limit to 4000 characters, which was then sufficient to parse the feed (which otherwise was a valid RSS feed without issues).
I'm not sure, if this PR is a desired solution to this problem. Because this might still break if some other feed has an even longer run-up to the tag that determines parsability. Also, the `2000` characters limit might have been there for a reason!?
Happy to solve this differently, if there are any suggestions for improvement.
✌️
=> Increasing slice limit regarding able_to_parse?

lib/feedjira/parser/json_feed.rb, spec/feedjira/parser/json_feed_spec.rb, spec/sample_feeds.rb, spec/sample_feeds/json_feed_with_escaped_uris.json
Hello again,
I found [a JSON feed](https://lukedorny.com/feed) which could actually be parsed just fine, but where feedjira wouldn't let me, because `able_to_parse?` returned `false` - which happened, because the feed's `version` contained the URL string with escaped slashes, like so: `https:\/\/jsonfeed.org\/version\/1.1`.
Since escaping slashes in JSON strings is apparently supported, I updated the responsible regex to match those optional escaping backslashes.
✌️
=> Enable parsing of JSON feeds with escaped version URL

lib/feedjira.rb
To be able to parse all feeds, regardless whether they meet the criteria somewhat early in the document
Sample JSON feed, that has the determining version statement right at the end: https://aaronparecki.com/feed.json.
@mockdeep Sorry, here we go [again](https://github.com/feedjira/feedjira/pull/514). 😬 Not quite sure, if removing the character limit like this is feasible, but I thought I present this suggestion to you regardless. 😊
=> Removing start_of_doc slice limit altogether

lib/feedjira/preprocessor.rb
It looks like [`CDATA`][cd] is mutually exclusive from content nodes. The
method `content_nodes` searches for `content`, `summary`, and `title`,
which are all of [type "element"][el].
[cd]: https://github.com/sparklemotion/nokogiri/blob/d29828c83fbc7ace24419c1f2aa91a9a17745462/lib/nokogiri/xml/node.rb#L1339-L1341
[el]: https://github.com/sparklemotion/nokogiri/blob/d29828c83fbc7ace24419c1f2aa91a9a17745462/lib/nokogiri/xml/node.rb#L1390-L1392
=> Coverage: remove condition in Preprocessor
